apiVersion: velero.io/v1
kind: Backup
metadata:
  # Backups need unique name
  generateName: test-
spec:
  defaultVolumesToFsBackup: false
  snapshotMoveData: false
  # The CSI snapshot should be quicker than the pg_sleep() period for pg_backup_start()
  csiSnapshotTimeout: 2m0s
  # Retention period for backup - Afterwards it's removed from OpenShift, Object Storage with related snapshots too.
  ttl: 24h0m0s
  # ttl: 0h15m0s
  # Async volume upload timeout
  itemOperationTimeout: 4h0m0s
  storageLocation: cloudnative-pg-oadp
  hooks:
    resources:
      - includedNamespaces:
          - postgres
        name: backup-start
        pre:
          - exec:
              command:
                - /bin/bash
                - '-c'
                - |
                  date +%T
                  echo pre-hook-log-start $(hostname)
                  # Sending stdout/err to /dev/null is required to avoid blocking the hook
                  psql -U postgres -c "SELECT pg_backup_start('oadp', true); SELECT pg_sleep(180); SELECT pg_backup_stop();" >/dev/null 2>&1 &
                  sleep 2 # Give some time for pg_backup_start()
                  date +%T
                  echo pre-hook-log-end $(hostname)
              container: postgres
              timeout: 60s
  includedNamespaces:
    - postgres
  labelSelector:
    matchExpressions:
      - key: cnpg.io/instanceRole
        operator: NotIn
        values:
          - replica
  # May not want to backup secrets if they are stored somewhere else and created by External Secrets Operator for example
  # excludedResources:
  #   - secrets
  
