apiVersion: velero.io/v1
kind: Restore
metadata:
  name: test-fr7vs-with-mapping
  namespace: openshift-adp
spec:
  backupName: test-fr7vs
  includedNamespaces:
    - postgres
  # If we want to restore in a different namespace
  namespaceMapping:
    postgres: postgres-restore 
  # It's better to let the cloudnative-pg operator recreate the Pods in the right order
  excludedResources:
    - pods
  restorePVs: true
  # Enforce patching the existing resources instead of skipping
  # existingResourcePolicy: update
  itemOperationTimeout: 4h0m0s